//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTS_EQUIPMENT
    {
        public int ID { get; set; }
        public string CONTACTS_CODE { get; set; }
        public string CONTACTS_CATEGORIES_CODE { get; set; }
        public string EQUI_CODE { get; set; }
        public Nullable<int> EQUI_QUANTITY { get; set; }
        public Nullable<int> EQUI_AMOUNT { get; set; }
    
        public virtual CONTACTS_CATEGORIES CONTACTS_CATEGORIES { get; set; }
        public virtual CONTACTS_DATA CONTACTS_DATA { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
    }
}
