//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPMENT()
        {
            this.CONTACTS_EQUIPMENT = new HashSet<CONTACTS_EQUIPMENT>();
        }
    
        public string EQUI_CODE { get; set; }
        public string SUPPLIER_ID { get; set; }
        public string EQUI_NAME { get; set; }
        public Nullable<int> EQUI_WARRANTY { get; set; }
        public Nullable<int> EQUI_QUANTITY { get; set; }
        public string EQUI_UNIT { get; set; }
        public Nullable<int> EQUI_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTS_EQUIPMENT> CONTACTS_EQUIPMENT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
