//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_AccountPermission
    {
        public int AccountPermissionID { get; set; }
        public string GroupID { get; set; }
        public string Username { get; set; }
    
        public virtual Sys_Account Sys_Account { get; set; }
        public virtual Sys_GroupPermision Sys_GroupPermision { get; set; }
    }
}
