//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Action
    {
        public int Action_ID { get; set; }
        public Nullable<int> Controller_ID { get; set; }
        public string Action_Name { get; set; }
        public string Action_Name_Vi { get; set; }
        public string Action_Name_En { get; set; }
        public string Action_Name_Cn { get; set; }
    }
}
