//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_GroupPermisionDetail
    {
        public int GPD_Id { get; set; }
        public string GroupID { get; set; }
        public string Action_ID { get; set; }
    
        public virtual Sys_Action Sys_Action { get; set; }
        public virtual Sys_GroupPermision Sys_GroupPermision { get; set; }
    }
}
